project:
  type: website
  output-dir: docs

website:
  title: "kokoromi"
  page-navigation: true
  page-footer: "VVM"
  navbar:
    background: dark
    foreground: info
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  sidebar:
    style: "docked"
    search: true
    title: "kokoro"
    background: "#5c9e95"
    foreground: "#c7a3c0"
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Showcase"
        href: showcase.qmd
      - text: "Cuidado remunerado (viz)"
        href: uso-del-tiempo.qmd
      - text: "Web scraping"
        href: web-scraping.qmd
      - text: "Build a site like this"
        href: build-a-site.qmd
      - text: "About"
        href: about.qmd
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
editor:
  render-on-save: true


