project:
  type: website
  output-dir: docs

website:
  title: "kokoromi"
  page-navigation: true
  page-footer: "VVM"
  navbar:
    background: dark
    foreground: info
    left:
      - href: index.qmd
        text: Home
      - href: showcase.qmd
        text: Showcase
      - href: about.qmd
        text: About
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
editor:
  render-on-save: true


